@include('layouts.header')
<body class="archive post-type-archive post-type-archive-product custom-background wp-custom-logo wp-embed-responsive theme-storefront woocommerce-shop woocommerce woocommerce-page woocommerce-no-js storefront-full-width-content storefront-align-wide right-sidebar woocommerce-active layout- storefront-pro-active sfp-nav-styleright nav-items-right sfp-shop-layout pootle-page-customizer-active">

@include('common.menubar')


        <div id="content" class="site-content" tabindex="-1">
            <div class="col-full">

                <div class="woocommerce"></div>
                <div id="primary" class="content-area">
                    <main id="main" class="site-main" role="main">
                        <header class="woocommerce-products-header">
                            <h1 class="woocommerce-products-header__title page-title">Premade Sticker Store</h1>

                        </header>
                        <div class="storefront-sorting">
                            <div class="woocommerce-notices-wrapper"></div>
                            <form class="woocommerce-ordering" method="get">
                                <select name="orderby" class="orderby" aria-label="Shop order">
					<option value="menu_order"  selected='selected'>Default sorting</option>
					<option value="popularity" >Sort by popularity</option>
					<option value="rating" >Sort by average rating</option>
					<option value="date" >Sort by latest</option>
					<option value="price" >Sort by price: low to high</option>
					<option value="price-desc" >Sort by price: high to low</option>
			</select>
                                <input type="hidden" name="paged" value="1" />
                            </form>
                            <p class="woocommerce-result-count">
                                Showing all 13 results</p>
                        </div>
                        <div class="columns-4">
                            <ul class="products columns-4">
                                <li class="product type-product post-530 status-publish first instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/bearded-skull/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/skull_heads-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Bearded Skull</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-577 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/bears-beets-battlestar-galactica/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/bearsbeatsbattle-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Bears, Beets, Battlestar Galactica</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-524 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/black-and-white-owl/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/owl.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/owl-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/owl.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/owl.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/owl.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/owl-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Black and White Owl</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-583 status-publish last instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/boombox-radio-speakers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/radio.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/radio-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/radio.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/radio.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/radio.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/radio-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Boombox Radio Speakers</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-6168 status-publish first instock product_cat-premade-sticker has-post-thumbnail sale taxable shipping-taxable purchasable product-type-variable">
                                    <a href="https://www.sierrastickers.com/product/custom-christmas-labels-100pcs/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="324" height="324" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20324%20324'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-324x324.png 324w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-150x150.png 150w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-100x100.png 100w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-32x32.png 32w" data-lazy-sizes="(max-width: 324px) 100vw, 324px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-324x324.png" /><noscript><img width="324" height="324" src="https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-324x324.png" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-324x324.png 324w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-150x150.png 150w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-100x100.png 100w, https://www.sierrastickers.com/wp-content/uploads/2021/11/RED-Merry-Christmas-With-Love-Roll-Mockup-32x32.png 32w" sizes="(max-width: 324px) 100vw, 324px" /></noscript><h2 class="woocommerce-loop-product__title">Custom Christmas Labels 100pcs</h2>
	<span class="onsale">Sale!</span>
	
	<span class="price"><del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>55.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>30.00</bdi></span></ins></span>
</a></li>
                                <li class="product type-product post-526 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/for-fox-sake/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/fox.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/fox-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/fox.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/fox.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/fox.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/fox-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">For Fox Sake</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-528 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/pineapple-black-and-white/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/pineapple-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Pineapple Black and White</h2><span class="size">4"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-581 status-publish last instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/save-water-drink-rose/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/rose.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/rose-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/rose.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/rose.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/rose.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/rose-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Save Water Drink Rosé</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-532 status-publish first instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/sunflower/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/sunflower-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Sunflower</h2><span class="size">4"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-536 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/travel-more-mountains/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/travel_more-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Travel More Mountains</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-579 status-publish instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/wild-and-free-bear-trees/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/wildandfree-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Wild and Free Bear &#038; Trees</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-538 status-publish last instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/witches-be-trippin/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/witches.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/witches-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/witches.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/witches.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/witches.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/witches-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">Witches Be Trippin</h2><span class="size">3"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                                <li class="product type-product post-534 status-publish first instock product_cat-premade-sticker has-post-thumbnail taxable shipping-taxable purchasable product-type-simple">
                                    <a href="https://www.sierrastickers.com/product/you-belong-among-the-wildflowers/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img width="311" height="242" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20311%20242'%3E%3C/svg%3E" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" data-lazy-srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers-300x233.jpg 300w" data-lazy-sizes="(max-width: 311px) 100vw, 311px" data-lazy-src="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers.jpg" /><noscript><img width="311" height="242" src="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail" alt="" srcset="https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers.jpg 311w, https://www.sierrastickers.com/wp-content/uploads/2020/05/wildflowers-300x233.jpg 300w" sizes="(max-width: 311px) 100vw, 311px" /></noscript><h2 class="woocommerce-loop-product__title">You Belong Among the Wildflowers</h2><span class="size">4"</span>
	<span class="price"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>6.99</bdi></span></span>
</a></li>
                            </ul>
                        </div>
                        <div class="storefront-sorting">
                            <form class="woocommerce-ordering" method="get">
                                <select name="orderby" class="orderby" aria-label="Shop order">
					<option value="menu_order"  selected='selected'>Default sorting</option>
					<option value="popularity" >Sort by popularity</option>
					<option value="rating" >Sort by average rating</option>
					<option value="date" >Sort by latest</option>
					<option value="price" >Sort by price: low to high</option>
					<option value="price-desc" >Sort by price: high to low</option>
			</select>
                                <input type="hidden" name="paged" value="1" />
                            </form>
                            <p class="woocommerce-result-count">
                                Showing all 13 results</p>
                        </div>
                    </main>
                    <!-- #main -->
                </div>
                <!-- #primary -->


            </div>
            <!-- .col-full -->
        </div>
        <!-- #content -->

@include('layouts.footer');
</body>

</html>

<!-- This website is like a Rocket, isn't it? Performance optimized by WP Rocket. Learn more: https://wp-rocket.me -->